In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt # for plotting graphs
import seaborn as sns
% matplotlib inline

# Read CSV

In [24]:
csv_y_train = pd.read_csv("/Users/waddnaa/Desktop/TJ2018-AUDITION/y_train.csv")
csv_y_test_index = pd.read_csv("/Users/waddnaa/Desktop/TJ2018-AUDITION/y_test_index.csv")
csv_demo = pd.read_csv("/Users/waddnaa/Desktop/TJ2018-AUDITION/demo.csv")
csv_ard = pd.read_csv("/Users/waddnaa/Desktop/TJ2018-AUDITION/adr.csv")
csv_sa = pd.read_csv("/Users/waddnaa/Desktop/TJ2018-AUDITION/sa.csv")
csv_cc_txn = pd.read_csv("/Users/waddnaa/Desktop/TJ2018-AUDITION/cc_txn.csv")

In [52]:
mergeing1 = pd.merge(csv_y_train, csv_y_test_index, how='left')

In [51]:
mergeing2 = pd.merge(mergeing1, csv_demo, how='left')

In [50]:
mergeing3 = pd.merge(mergeing2,csv_ard, how='left')

In [49]:
mergeing4 = pd.merge(mergeing3,csv_sa, how='left')

In [48]:
mergeing5 = pd.merge(mergeing4,csv_cc_txn, how='left')

In [53]:
mergeing5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 287129 entries, 0 to 287128
Data columns (total 19 columns):
ip_id             287129 non-null int64
label             287129 non-null float64
brth_yr           287129 non-null float64
act_strt_dt       287129 non-null object
no_of_dpnd_chl    287129 non-null float64
cis_income        287129 non-null float64
crn_bal           287129 non-null float64
gnd_cd            287129 non-null float64
mar_st_cd         287129 non-null float64
ctf_tp_cd         287129 non-null float64
ocp_cd            287129 non-null int64
prov              159200 non-null object
dt                287129 non-null object
channel           287129 non-null object
tp                287129 non-null object
amt               287129 non-null float64
category          64499 non-null object
card              64499 non-null object
txn_amt           64499 non-null float64
dtypes: float64(10), int64(2), object(7)
memory usage: 43.8+ MB

In [54]:
mergeing5

,ip_id,label,brth_yr,act_strt_dt,no_of_dpnd_chl,cis_income,crn_bal,gnd_cd,mar_st_cd,ctf_tp_cd,ocp_cd,prov,dt,channel,tp,amt,category,card,txn_amt
0,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-02-06,EDC,DR,1045.0,cat15,card2,9786.0
1,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-02-28,Branch,CR,995.0,cat7,card1,2415.0
2,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-03-15,KPlus,DR,6311.0,cat14,card3,4564.0
3,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-03-15,KPlus,DR,6311.0,cat9,card1,1486.0
4,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-03-22,KPlus,CR,884.0,NaN,NaN,NaN
5,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-03-26,Branch,DR,4890.0,NaN,NaN,NaN
6,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-03-29,ATM,CR,5955.0,NaN,NaN,NaN
7,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-03-30,CDM,CR,6879.0,NaN,NaN,NaN
8,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-04-02,CorporateConnect,CR,3082.0,cat1,card2,1447.0
9,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-04-10,ATM,DR,735.0,cat5,card1,5922.0
10,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-04-20,ATM,DR,1278.0,NaN,NaN,NaN
11,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-04-22,KPlus,DR,14607.0,NaN,NaN,NaN
12,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-04-29,ATM,CR,6426.0,NaN,NaN,NaN
13,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-05-03,CDM,CR,17431.0,NaN,NaN,NaN
14,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-05-12,CorporateConnect,CR,8.0,NaN,NaN,NaN
15,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-06-01,KPlus,DR,1410.0,NaN,NaN,NaN
16,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-06-05,Branch,DR,3635.0,NaN,NaN,NaN
17,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-06-06,Branch,DR,2918.0,cat2,card1,2211.0
18,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-06-18,CDM,CR,1446.0,cat15,card1,5148.0
19,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-07-30,CorporateConnect,CR,8811.0,NaN,NaN,NaN
20,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-08-09,ATM,CR,6840.0,cat14,card3,6928.0
21,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-08-10,KPlus,DR,4232.0,NaN,NaN,NaN
22,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-08-16,EDC,DR,910.0,NaN,NaN,NaN
23,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-09-02,CDM,CR,6116.0,NaN,NaN,NaN
24,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-09-11,CorporateConnect,DR,161.0,NaN,NaN,NaN
25,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-09-13,KPlus,CR,13093.0,NaN,NaN,NaN
26,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-10-01,CorporateConnect,DR,47.0,NaN,NaN,NaN
27,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-10-12,Branch,CR,4172.0,cat9,card1,1522.0
28,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-10-17,KPlus,DR,9452.0,NaN,NaN,NaN
29,1,0.0,1990.0,2011-12-11,0.0,45864.0,876428.0,2.0,2.0,3.0,9,NaN,2017-10-19,KPlus,CR,6770.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287099,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-04-21,KPlus,CR,47750.0,NaN,NaN,NaN
287100,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-05-18,CorporateConnect,CR,18847.0,NaN,NaN,NaN
287101,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-05-28,CorporateConnect,DR,7742.0,cat8,card3,30522.0
287102,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-06-13,Branch,CR,40382.0,NaN,NaN,NaN
287103,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-06-20,CorporateConnect,CR,22729.0,NaN,NaN,NaN
287104,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-07-23,CDM,CR,7671.0,NaN,NaN,NaN
287105,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-07-25,CorporateConnect,DR,49223.0,NaN,NaN,NaN
287106,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-08-01,CDM,CR,18477.0,cat14,card1,24719.0
287107,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-08-19,Branch,CR,30241.0,cat3,card1,12698.0
287108,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-09-09,CorporateConnect,DR,14920.0,NaN,NaN,NaN
287109,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-09-10,Branch,DR,36224.0,NaN,NaN,NaN
287110,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-09-17,Branch,CR,6990.0,NaN,NaN,NaN
287111,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-09-23,CDM,CR,14553.0,NaN,NaN,NaN
287112,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-10-11,EDC,DR,43284.0,NaN,NaN,NaN
287113,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-10-15,Branch,CR,24260.0,NaN,NaN,NaN
287114,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-10-27,EDC,DR,50813.0,NaN,NaN,NaN
287115,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-12-01,CorporateConnect,CR,22493.0,NaN,NaN,NaN
287116,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-12-02,KPlus,DR,10236.0,NaN,NaN,NaN
287117,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-12-03,Branch,DR,24801.0,cat8,card1,27045.0
287118,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-12-07,Branch,DR,12905.0,NaN,NaN,NaN
287119,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-12-12,KPlus,CR,16960.0,NaN,NaN,NaN
287120,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-12-21,EDC,DR,2656.0,NaN,NaN,NaN
287121,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-12-22,CDM,CR,38646.0,NaN,NaN,NaN
287122,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2017-12-23,CorporateConnect,DR,2641.0,cat14,card2,15619.0
287123,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2018-01-07,CDM,CR,4382.0,NaN,NaN,NaN
287124,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2018-01-24,Branch,DR,11307.0,NaN,NaN,NaN
287125,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2018-01-24,KPlus,CR,51025.0,NaN,NaN,NaN
287126,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2018-01-26,CorporateConnect,DR,20769.0,cat7,card1,67774.0
287127,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2018-02-03,CDM,CR,57599.0,NaN,NaN,NaN
287128,6361,1.0,1972.0,1999-05-03,0.0,42673.0,500.0,2.0,2.0,4.0,3,สุรินทร์,2018-02-11,Branch,CR,24783.0,NaN,NaN,NaN